packages:
  - "../apps/*"
  - "../packages/*"
  - "../packages/plugins/*"
  - "../poc/edgesync-protocol"
  - "../tests/frontend/unit/*"
  - "../tests/frontend/integration/*"
allowBuilds:
  esbuild: set this to true or false
