// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Savoire.Infrastructure.Persistence;

#nullable disable

namespace Savoire.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806102944_AddManagedVaults")]
    partial class AddManagedVaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Savoire.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrivateKeyHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultKeyHex")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Savoire.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.EdgesyncBlobEntity", b =>
                {
                    b.Property<string>("VaultId")
                        .HasColumnType("TEXT")
                        .HasColumnName("vault_id");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("VaultId", "Key");

                    b.ToTable("edgesync_blobs", (string)null);
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.FolderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("VaultId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vault_id");

                    b.HasKey("Id");

                    b.HasIndex("VaultId")
                        .HasDatabaseName("idx_folders_vault");

                    b.HasIndex("VaultId", "Path")
                        .IsUnique();

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.IndexSnapshotEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("namespace");

                    b.Property<long>("ProcessedSeq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("processed_seq");

                    b.Property<string>("VaultId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vault_id");

                    b.HasKey("Id");

                    b.HasIndex("VaultId", "Namespace")
                        .HasDatabaseName("idx_snapshots_vault_ns");

                    b.ToTable("index_snapshots", (string)null);
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.ManagedVaultKeyringEntity", b =>
                {
                    b.Property<string>("VaultId")
                        .HasColumnType("TEXT")
                        .HasColumnName("vault_id");

                    b.Property<byte[]>("KeyringBytes")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("keyring_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("VaultId");

                    b.ToTable("managed_vault_keyrings", (string)null);
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.OperationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<byte[]>("OpBytes")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("op_bytes");

                    b.Property<DateTime>("ProducedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("produced_at");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_type");

                    b.HasKey("Id");

                    b.HasIndex("ResourceType", "ResourceId", "ReceivedAt")
                        .HasDatabaseName("idx_ops_resource");

                    b.ToTable("operations_log", (string)null);
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.RefPermissionEntity", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.HasKey("Value");

                    b.ToTable("ref_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Value = "read",
                            Description = "Read-only access to the resource."
                        },
                        new
                        {
                            Value = "write",
                            Description = "Read and write access to the resource."
                        },
                        new
                        {
                            Value = "admin",
                            Description = "Full control, including sharing the resource."
                        });
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.RefResourceTypeEntity", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.HasKey("Value");

                    b.ToTable("ref_resource_types", (string)null);

                    b.HasData(
                        new
                        {
                            Value = "vault",
                            Description = "A vault — contains documents and folders."
                        },
                        new
                        {
                            Value = "document",
                            Description = "A single document within a vault."
                        });
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.RefSubjectTypeEntity", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.HasKey("Value");

                    b.ToTable("ref_subject_types", (string)null);

                    b.HasData(
                        new
                        {
                            Value = "user",
                            Description = "An individual user account."
                        });
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.RefSyncChangeTypeEntity", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.HasKey("Value");

                    b.ToTable("ref_sync_change_types", (string)null);

                    b.HasData(
                        new
                        {
                            Value = "created",
                            Description = "Document was created after the sync baseline."
                        },
                        new
                        {
                            Value = "modified",
                            Description = "Document was modified after the sync baseline."
                        },
                        new
                        {
                            Value = "deleted",
                            Description = "Document was soft-deleted after the sync baseline."
                        },
                        new
                        {
                            Value = "moved",
                            Description = "Document was moved (reserved — not yet produced by the server)."
                        });
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.RefVaultRoleEntity", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.HasKey("Value");

                    b.ToTable("ref_vault_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Value = "owner",
                            Description = "Vault creator — cannot be removed, has all permissions."
                        },
                        new
                        {
                            Value = "editor",
                            Description = "Can read and write documents."
                        },
                        new
                        {
                            Value = "viewer",
                            Description = "Read-only access to all documents in the vault."
                        });
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.ResourcePermissionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("granted_by");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("permission");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_type");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_type");

                    b.HasKey("Id");

                    b.HasIndex("Permission");

                    b.HasIndex("SubjectType");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("idx_rp_resource");

                    b.HasIndex("ResourceType", "ResourceId", "SubjectType", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("IX_resource_permissions_unique");

                    b.ToTable("resource_permissions", (string)null);
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.ShareLinkEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("permission");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_type");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("Permission");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_share_links_token");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("idx_sl_resource");

                    b.ToTable("share_links", (string)null);
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.SyncVectorEntity", b =>
                {
                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_id");

                    b.Property<string>("ClientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<byte[]>("Vector")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("vector");

                    b.HasKey("ResourceId", "ClientId");

                    b.ToTable("sync_vectors", (string)null);
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.VaultEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsManaged")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_managed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.ToTable("vaults", (string)null);
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.VaultKeyWrapEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("VaultId")
                        .HasColumnType("TEXT")
                        .HasColumnName("vault_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<byte[]>("WrappedKeyBytes")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("wrapped_key_bytes");

                    b.HasKey("UserId", "VaultId");

                    b.ToTable("vault_key_wraps", (string)null);
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.VaultMemberEntity", b =>
                {
                    b.Property<string>("VaultId")
                        .HasColumnType("TEXT")
                        .HasColumnName("vault_id");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("VaultId", "UserId");

                    b.HasIndex("Role");

                    b.ToTable("vault_members", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Savoire.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Savoire.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Savoire.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Savoire.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.FolderEntity", b =>
                {
                    b.HasOne("Savoire.Infrastructure.Persistence.VaultEntity", "Vault")
                        .WithMany("Folders")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.ResourcePermissionEntity", b =>
                {
                    b.HasOne("Savoire.Infrastructure.Persistence.RefPermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("Permission")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Savoire.Infrastructure.Persistence.RefResourceTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("ResourceType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Savoire.Infrastructure.Persistence.RefSubjectTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("SubjectType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.ShareLinkEntity", b =>
                {
                    b.HasOne("Savoire.Infrastructure.Persistence.RefPermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("Permission")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Savoire.Infrastructure.Persistence.RefResourceTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("ResourceType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.VaultMemberEntity", b =>
                {
                    b.HasOne("Savoire.Infrastructure.Persistence.RefVaultRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Savoire.Infrastructure.Persistence.VaultEntity", "Vault")
                        .WithMany("Members")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Savoire.Infrastructure.Persistence.VaultEntity", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
