// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Jean Leloup
export type {
  PluginManifest,
  PluginPermission,
  VaultPlugin,
  IPluginAPI,
  IPluginVaultAPI,
  IPluginWorkspaceAPI,
  IPluginCommandsAPI,
  IPluginViewsAPI,
  IPluginBlocksAPI,
  IPluginHooksAPI,
  IPluginSlashAPI,
  IPluginTriggersAPI,
  IPluginEditorAPI,
  IPluginToolbarAPI,
  PluginAPI,
  PluginCommandContext,
  PluginCommand,
  CommandRegistry,
  HookStage,
  HookRegistry,
  BlockWidget,
  BlockContext,
  BlockSpec,
  BlockRegistry,
  FileContext,
  FileView,
  FileTypeSpec,
  FileTypeRegistry,
  VaultAPI,
  ViewDocument,
  WorkspaceAPI,
  BlockTrigger,
  SlashCommandItem,
  SlashRegistry,
  InputTrigger,
  TriggerRegistry,
  TriggerItem,
  TriggerActivation,
  TriggerHandler,
  EditorPositionAPI,
  EditorCommandContext,
  ToolbarCommand,
  ToolbarCommandRegistry,
  Widget,
  ViewContext,
  ViewSpec,
  ViewGroup,
  ViewRegistry,
  DocumentRoom,
  DocumentRoomPresence,
  SyncAPI,
  PluginLoadStrategy,
  NotePluginScope,
  NoteScope,
  ContentExtractor,
  IndexContributor,
  ICollaborativeText,
  IndexEntry,
  RelPosJSON,
  IPluginIndexAPI,
  IIndexContributorRegistry,
  IIndexRegistry,
  IEditorHostAPI,
  IPluginLoader,
  CrdtVersion,
  DocMetadata,
  FileTreeEntry,
} from './types'

// Runtime values from domain-index re-exported via indexing.ts
export { AnchorIndex, resolveEntry, validateEntry, anchorKey } from './indexing'

export type { ICRDT } from './crdt'
export type { ITransport } from './transport'
